In [1]:
import pandas as pd
from sklearn.decomposition import PCA

# Fuction for PCA calculation

In [5]:
def pca(dataframe, eq_id, parameters):
    n_components = 2
    res = pd.DataFrame()
    df = dataframe[dataframe.id == eq_id]
    res = df[['id', 'date', 'nday', 'h', 'm'] + parameters]
    X = df.drop(columns=['id', 'date']).to_numpy()
    pca = PCA(n_components=n_components)
    components = pd.DataFrame(pca.fit_transform(X))
    res.reset_index(drop=True, inplace=True)
    components.reset_index(drop=True, inplace=True)
    components.columns = ['comp_1', 'comp_2']
    return pd.concat([res, components],axis=1)

## Example

In [6]:
path_in = '../../ionosphere_dataset/NOAA/NOAA_datasets_for_ML/dataset_NN_model/sondes_in_ml.csv'
df_inside = pd.read_csv(path_in, sep=',')
cols_non_nan = ['foF2', 'M(D)', 'MUF(D)', 'fmin', 'foEs', 'fminF', 'fxI', "h'F", "h'F2", "h'Es", 'D', 'foEp', 'peak height of F2 layer',
 'foF2p','id', 'date', 'nday', 'h', 'm']
df_inside = df_inside[cols_non_nan]

In [8]:
df_with_components = pca(df_inside, 'ak0028jvqcwp', ['foF2', "h'Es"])
df_with_components.head(10)

             id        date  nday  h   m   foF2   h'Es      comp_1     comp_2
0  ak0028jvqcwp  2002-06-21  14.0  0   0  6.413  100.0  258.526496  26.634657
1  ak0028jvqcwp  2002-06-21  14.0  0  30  5.925  101.0   86.900494 -16.221096
2  ak0028jvqcwp  2002-06-21  14.0  1   0  6.050   96.0   32.946904 -17.371801
3  ak0028jvqcwp  2002-06-21  14.0  1  30  5.950   93.0   12.201855 -43.159249
4  ak0028jvqcwp  2002-06-21  14.0  2   0  7.550   95.0    4.776586  30.059867
5  ak0028jvqcwp  2002-06-21  14.0  2  30  5.950   93.0   -0.740916  -8.538049
6  ak0028jvqcwp  2002-06-21  14.0  3   0  5.750   88.0 -155.542990 -26.212803
7  ak0028jvqcwp  2002-06-21  14.0  3  30  5.450   95.0 -116.817387 -43.711961
8  ak0028jvqcwp  2002-06-21  14.0  4   0  8.050  100.0   21.264829  31.704746
9  ak0028jvqcwp  2002-06-21  14.0  4  30  5.650  130.0   78.836749 -21.310449